spring:
  jpa:
    database: sql_server
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    url: jdbc:sqlserver://DESKTOP-UOQ7755:1433;database=DOANWEB;encrypt=false
    password: vdt1410
  security:
    user:
      name: vuducthang
      password: 12345678
      roles: admin
    oauth2:
      resource-server:
        opaque-token:
          client-id: 930582761358-3sl6m5nvakqs9bjqdoo8mt2q51iqkolu.apps.googleusercontent.com
          client-secret: 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
          introspection-uri: https://www.googleapis.com/
  thymeleaf:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: vut70141@gmail.com
    password: kcwocspqgjtorhya
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8888

jwt:
  secret: SgTPK0QnzgiFKOPQX2WbQo54cd0lKoLNuaguasyajsjhdgasdgyugaufubbewuegkHHGSGhajhafasffa
  accessTokenExpirationMs: 60000
  refreshTokenExpirationMs: 86400000

frontend:
  url: http://localhost:3000



