spring:
  jpa:
    database: sql_server
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    url: jdbc:sqlserver://DESKTOP-UOQ7755:1433;database=DOANWEB;encrypt=false
    password: vdt1410
  security:
    user:
      name: vuducthang
      password: 12345678
      roles: admin
  thymeleaf:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: vut70141@gmail.com
    password: kcwocspqgjtorhya
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8888

jwt:
  secret: SgTPK0QnzgiFKOPQX2WbQo54cd0lKoLN
  accessTokenExpirationMs: 60000
  refreshTokenExpirationMs: 86400000



