spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        envers.audit_table_suffix: _AUD
        envers.revision_field_name: REV
        envers.revision_type_field_name: REV_TYPE
        envers.audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    url: ${DB_URL:jdbc:mysql://localhost:3306/SocialNetwork}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    password: ${DB_PASSWORD:123456}
  security:
    user:
      name: vuducthang
      password: 12345678
      roles: admin
    oauth2:
      resource-server:
        opaque-token:
          client-id: 930582761358-3sl6m5nvakqs9bjqdoo8mt2q51iqkolu.apps.googleusercontent.com
          client-secret: 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
          introspection-uri: https://www.googleapis.com/
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: vut70141@gmail.com
    password: kcwocspqgjtorhya
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: SgTPK0QnzgiFKOPQX2WbQo54cd0lKoLNuaguasyajsjhdgasdgyugaufubbewuegkHHGSGhajhafasffa
  accessTokenExpirationMs: 6000000
  refreshTokenExpirationMs: 86400000

frontend:
  url: http://localhost:3000
  url-reset-password: http://localhost:3000/reset-password
server.ssl.enabled: false

#OPENVIDU_URL: http://localhost:4443/
#OPENVIDU_SECRET: MY_SECRET
#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.web.socket: DEBUG
#    org.springframework.messaging: DEBUG
#



